#!/bin/bash
#
# Copyright 2016 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

if [ "$1" = "purge" ] ; then
    update-rc.d gocd-golang-agent remove >/dev/null || exit $?

    rm -fr /usr/share/gocd-golang-agent
    rm -fr /var/lib/gocd-golang-agent
    rm -fr /var/run/gocd-golang-agent
    rm -fr /var/log/gocd-golang-agent

    GO_AGENT_DEFAULTS=/etc/default/gocd-golang-agent
    if [ -L $GO_AGENT_DEFAULTS ]; then
        rm $GO_AGENT_DEFAULTS
    fi
fi
