#!/bin/bash
#*************************GO-LICENSE-START********************************
# Copyright 2014 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*************************GO-LICENSE-END**********************************

set -x
### BEGIN INIT INFO
# Provides: gocd-agent
# Required-Start: $network $remote_fs
# Required-Stop: $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start the GOCD Agent
### END INIT INFO
NAME="gocd-agent"
PIDFILE="/var/run/gocd-agent/gocd-agent.pid"
DAEMON="/usr/bin/gocd-agent"

. /etc/default/gocd-agent

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
	/sbin/start-stop-daemon --start -c go:go -m --quiet --pidfile $PIDFILE --background --exec $DAEMON
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	/sbin/start-stop-daemon --stop -c go:go --quiet --oknodo --pidfile $PIDFILE
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME
	/sbin/start-stop-daemon --stop -c go:go --quiet --oknodo --retry 30 --pidfile $PIDFILE
	/sbin/start-stop-daemon --start -c go:go -m --quiet --pidfile $PIDFILE --background --exec $DAEMON -- $DAEMON_OPTS
	echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac
exit 0
